# Generated by Django 5.2.12 on 2026-04-05 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reseller',
            name='es_super',
            field=models.BooleanField(default=False, help_text='Puede crear otros Resellers'),
        ),
        migrations.AddField(
            model_name='reseller',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_resellers', to='panel.reseller'),
        ),
        migrations.AlterField(
            model_name='canal',
            name='url_origen',
            field=models.URLField(),
        ),
    ]
