# Generated by Django 5.2.12 on 2026-04-07 04:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_reseller_es_super_reseller_padre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='horas',
            field=models.IntegerField(default=0, help_text='Usar solo para demos/trials'),
        ),
        migrations.AddField(
            model_name='usuarioiptv',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plan',
            name='meses',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reseller',
            name='es_super',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuarioiptv',
            name='fecha_expiracion',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuarioiptv',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usuarioiptv',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.plan'),
        ),
        migrations.AlterField(
            model_name='usuarioiptv',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
