# Generated by Django 5.2.12 on 2026-04-07 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_plan_horas_usuarioiptv_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioiptv',
            name='ultima_actividad',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='horas',
            field=models.IntegerField(default=0),
        ),
    ]
