# Generated by Django 5.2.12 on 2026-04-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_usuarioiptv_ultima_actividad_alter_plan_horas'),
    ]

    operations = [
        migrations.AddField(
            model_name='reseller',
            name='password_plano',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
